from header import *
from dialogs import *

class MainWindow(QtWidgets.QMainWindow):

        def __init__(self):
                super().__init__()
                if not self.objectName():
                        self.setObjectName(u"MainWindow")
                self.setWindowModality(Qt.ApplicationModal)
                self.setFixedSize(720, 480)
                palette = QPalette()
                brush = QBrush(QColor(0, 0, 0, 255))
                brush.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
                brush1 = QBrush(QColor(227, 195, 253, 199))
                brush1.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.Button, brush1)
                brush2 = QBrush(QColor(255, 255, 255, 199))
                brush2.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.Light, brush2)
                brush3 = QBrush(QColor(241, 225, 254, 199))
                brush3.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
                brush4 = QBrush(QColor(113, 97, 127, 199))
                brush4.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
                brush5 = QBrush(QColor(151, 130, 169, 199))
                brush5.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
                palette.setBrush(QPalette.Active, QPalette.Text, brush)
                brush6 = QBrush(QColor(255, 255, 255, 255))
                brush6.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
                palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
                palette.setBrush(QPalette.Active, QPalette.Base, brush6)
                palette.setBrush(QPalette.Active, QPalette.Window, brush1)
                palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
                brush7 = QBrush(QColor(241, 225, 254, 227))
                brush7.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
                brush8 = QBrush(QColor(255, 255, 220, 255))
                brush8.setStyle(Qt.SolidPattern)
                palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
                palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
                brush9 = QBrush(QColor(0, 0, 0, 128))
                brush9.setStyle(Qt.SolidPattern)
                #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
                palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
                #endif
                palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
                palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
                palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
                palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
                palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
                palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
                palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
                palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
                palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
                palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
                palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
                palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
                palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush7)
                palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
                palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
                #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
                palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
                #endif
                palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
                palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
                palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
                palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
                palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
                palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
                palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
                palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
                palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
                palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
                palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
                palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
                palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
                palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
                palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
                #if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
                palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
                #endif
                self.setPalette(palette)
                font = QFont()
                font.setFamily(u"Helvetica Neue")
                font.setPointSize(14)
                self.setFont(font)
                self.setStyleSheet(u"Fusion")
                self.actionAdd_New_Account = QAction(self)
                self.actionAdd_New_Account.setObjectName(u"actionAdd_New_Account")
                self.actionClose = QAction(self)
                self.actionClose.setObjectName(u"actionClose")
                self.actionAbout = QAction(self)
                self.actionAbout.setObjectName(u"actionAbout")
                self.centralwidget = QWidget(self)
                self.centralwidget.setObjectName(u"centralwidget")
                self.gridLayoutWidget = QWidget(self.centralwidget)
                self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
                self.gridLayoutWidget.setGeometry(QRect(240, 80, 258, 72))
                self.gridLayout = QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setObjectName(u"gridLayout")
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.service_input = QLineEdit(self.gridLayoutWidget)
                self.service_input.setObjectName(u"passwrod_row")
                sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(32)
                sizePolicy.setHeightForWidth(self.service_input.sizePolicy().hasHeightForWidth())
                self.service_input.setSizePolicy(sizePolicy)
                self.service_input.setMinimumSize(QSize(200, 36))
                self.service_input.setFont(QFont(size=32))

                self.gridLayout.addWidget(self.service_input, 1, 0, 1, 1)

                self.label = QLabel(self.gridLayoutWidget)
                self.label.setObjectName(u"label")
                font1 = QFont()
                font1.setFamily(u"Helvetica Neue")
                font1.setPointSize(24)
                self.label.setFont(font1)
                self.label.setAutoFillBackground(False)
                self.label.setStyleSheet(u"Fusion")
                self.label.setScaledContents(False)

                self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

                self.gridLayoutWidget_2 = QWidget(self.centralwidget)
                self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
                self.gridLayoutWidget_2.setGeometry(QRect(240, 170, 258, 72))
                self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
                self.gridLayout_2.setObjectName(u"gridLayout_2")
                self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
                self.add_info_input = QLineEdit(self.gridLayoutWidget_2)
                self.add_info_input.setObjectName(u"target_row")
                sizePolicy.setHeightForWidth(self.add_info_input.sizePolicy().hasHeightForWidth())
                self.add_info_input.setSizePolicy(sizePolicy)
                self.add_info_input.setMinimumSize(QSize(200, 36))
                self.add_info_input.setFont(QFont(size=32))

                self.gridLayout_2.addWidget(self.add_info_input, 1, 0, 1, 1)

                self.label_2 = QLabel(self.gridLayoutWidget_2)
                self.label_2.setObjectName(u"label_2")
                self.label_2.setFont(font1)
                self.label_2.setAutoFillBackground(False)
                self.label_2.setStyleSheet(u"Fusion")
                self.label_2.setScaledContents(False)

                self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)

                self.main_ok_button = QPushButton(self.centralwidget)
                self.main_ok_button.setObjectName(u"main_ok_button")
                self.main_ok_button.setGeometry(QRect(240, 270, 100, 30))
                font2 = QFont()
                font2.setFamily(u"Helvetica Neue")
                font2.setPointSize(18)
                self.main_ok_button.setFont(font2)
                self.main_ok_button.setAutoFillBackground(False)
                self.main_ok_button.setInputMethodHints(Qt.ImhNone)
                self.main_ok_button.setAutoDefault(True)
                self.main_reset_button = QPushButton(self.centralwidget)
                self.main_reset_button.setObjectName(u"main_reset_button")
                self.main_reset_button.setGeometry(QRect(400, 270, 100, 30))
                self.main_reset_button.setFont(font2)
                self.setCentralWidget(self.centralwidget)
                self.menubar = QMenuBar(self)
                self.menubar.setObjectName(u"menubar")
                self.menubar.setGeometry(QRect(0, 0, 720, 22))
                self.menuFile = QMenu(self.menubar)
                self.menuFile.setObjectName(u"menuFile")
                self.menuHelp = QMenu(self.menubar)
                self.menuHelp.setObjectName(u"menuHelp")
                self.setMenuBar(self.menubar)
                self.statusbar = QStatusBar(self)
                self.statusbar.setObjectName(u"statusbar")
                self.setStatusBar(self.statusbar)

                self.menubar.addAction(self.menuFile.menuAction())
                self.menubar.addAction(self.menuHelp.menuAction())
                self.menuFile.addAction(self.actionAdd_New_Account)
                self.menuFile.addAction(self.actionClose)
                self.menuHelp.addAction(self.actionAbout)

                self.actionAbout.triggered.connect(self.onAboutButtonClicked)
                self.main_ok_button.clicked.connect(self.getResult)
                self.main_reset_button.clicked.connect(self.resetRows)
                self.retranslateUi()

                QMetaObject.connectSlotsByName(self)
        
        def onAboutButtonClicked(self):
                dlg = showAboutDialog(self)
                dlg.exec_()

        def getResult(self):
                res = DataBase()
                if (len(self.add_info_input.text()) == 0):
                        res.selectFromDB(self.service_input.text())
                else:
                        res.selectFromDB(self.service_input.text(), self.add_info_input.text())
                dlg = showResultDialog()
                dlg.showDialog(res)
                dlg.exec_()

        def resetRows(self):
                self.service_input.setText('')
                self.add_info_input.setText('')


        def retranslateUi(self):
                self.setWindowTitle(QCoreApplication.translate("MainWindow", title, None))
                self.actionAdd_New_Account.setText(QCoreApplication.translate("MainWindow", u"Add New Account", None))
                self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
                self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
                self.label.setText(QCoreApplication.translate("MainWindow", u"Service", None))
                self.label_2.setText(QCoreApplication.translate("MainWindow", u"Additional info (optional)", None))
                #if QT_CONFIG(tooltip)
                self.main_ok_button.setToolTip("")
                #endif // QT_CONFIG(tooltip)
                #if QT_CONFIG(whatsthis)
                self.main_ok_button.setWhatsThis("")
                #endif // QT_CONFIG(whatsthis)
                self.main_ok_button.setText(QCoreApplication.translate("MainWindow", u"OK", None))
                self.main_reset_button.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
                self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
                self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))